#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Stop any time with Ctrl-C and re-run later — already-flashed%s\n' "$DIM" "$RESET"
  printf '%s  halves are skipped automatically if you confirm to reuse them.%s\n\n' "$DIM" "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ All done%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "not covered by this wizard:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="zmkfirmware/zmk-build-arm:stable"
LEFT_UF2="$REPO_ROOT/build/left/zephyr/zmk.uf2"
RIGHT_UF2="$REPO_ROOT/build/right/zephyr/zmk.uf2"

TOTAL_STAGES=3

banner "Sofle Choc Pro — flash firmware"

# _wait_for_boot_drive — poll /Volumes for a newly mounted bootloader drive
# (name containing "boot", case-insensitive). Echoes the mount path, or
# returns 1 on timeout. Pass the pre-mount volume listing as $1.
_wait_for_boot_drive() {
  local before="$1" i found
  for i in $(seq 1 120); do
    found=$(comm -13 \
      <(printf '%s\n' "$before" | sort) \
      <(ls /Volumes 2>/dev/null | sort) \
      | grep -i boot | head -1 || true)
    if [[ -n "$found" ]]; then
      printf '%s' "/Volumes/$found"
      return 0
    fi
    sleep 1
  done
  return 1
}

# _flash_half NAME UF2 — guide one half through reset + copy.
_flash_half() {
  local name="$1" uf2="$2" mount
  step "Unplug all USB cables, then plug in ONLY the $name half."
  pause "Press Enter once the $name half is connected..."
  note "Volumes now mounted: $(ls /Volumes 2>/dev/null | tr '\n' ' ')"
  say "Now put the $name half into bootloader mode, one of:"
  step "If the new firmware is already on it: toggle the SYS layer (SYS key,"
  say "  bottom-right of BASE), then press RST (bottom row, next to BOOT)."
  step "Otherwise: double-tap the physical reset button on the board."
  local before; before=$(ls /Volumes 2>/dev/null)
  pause "Press Enter right after triggering the reset..."
  if mount=$(_wait_for_boot_drive "$before"); then
    ok "bootloader drive mounted: $mount"
    step "Copying firmware ($uf2) ..."
    cp "$uf2" "$mount/" && sync
    ok "copied. The drive should eject itself and the keyboard reboots."
    pause "Press Enter once the drive has disappeared..."
    warn "If the drive is still there, eject it manually and re-plug the half."
  else
    warn "No bootloader drive appeared within 2 minutes."
    ask mount "Type the mount path manually (e.g. /Volumes/XIAO-BOOT), or Enter to skip:"
    if [[ -n "$mount" && -d "$mount" ]]; then
      cp "$uf2" "$mount/" && sync
      ok "copied to $mount"
    else
      SKIPPED+=("flashing the $name half — do it by hand: drag $uf2 onto the bootloader drive")
      warn "skipped flashing the $name half"
    fi
  fi
}

# ── Stage 1: build ────────────────────────────────────────────────────────
stage "Build firmware"
REBUILD=0
if [[ -f "$LEFT_UF2" && -f "$RIGHT_UF2" ]]; then
  note "existing firmware:"
  note "  left : $LEFT_UF2  ($(date -r "$LEFT_UF2" '+%Y-%m-%d %H:%M'))"
  note "  right: $RIGHT_UF2  ($(date -r "$RIGHT_UF2" '+%Y-%m-%d %H:%M'))"
  if confirm "Rebuild (pick this after keymap changes)?"; then
    REBUILD=1
  fi
fi
if [[ "$REBUILD" -eq 1 || ! -f "$LEFT_UF2" || ! -f "$RIGHT_UF2" ]]; then
  if ! command -v docker >/dev/null 2>&1; then
    warn "docker not found — install Docker Desktop first, then re-run."
    SKIPPED+=("build — docker missing")
    exit 1
  fi
  for side in left right; do
    say "Building sofle_choc_pro_${side} (this takes a few minutes)..."
    docker run --rm -v "$REPO_ROOT":/workspaces/zmk-config -w /workspaces/zmk-config \
      "$IMAGE" \
      west build -s zmk/app -b "sofle_choc_pro_${side}" -d "build/${side}" \
        -- -DZMK_CONFIG=/workspaces/zmk-config/config
  done
  [[ -f "$LEFT_UF2" && -f "$RIGHT_UF2" ]] || { warn "build failed — no .uf2 produced"; exit 1; }
  ok "firmware ready"
else
  ok "reusing existing firmware"
fi

# ── Stage 2: left half ────────────────────────────────────────────────────
stage "Flash left half"
_flash_half "left" "$LEFT_UF2"

# ── Stage 3: right half ───────────────────────────────────────────────────
stage "Flash right half"
_flash_half "right" "$RIGHT_UF2"

# Closing notes
SKIPPED+=("Bluetooth pairing — reconnect via USB or pair 'Sofle Choc Pro' in Bluetooth settings")
SKIPPED+=("If BT acts up after flashing: build & flash the settings_reset firmware on BOTH halves (docker run --rm -v \"\$PWD\":/workspaces/zmk-config -w /workspaces/zmk-config zmkfirmware/zmk-build-arm:stable west build -s zmk/app -b sofle_choc_pro_left -- -DSHIELD=settings_reset -DZMK_CONFIG=/workspaces/zmk-config/config), reflash normal firmware, then re-pair")

finish
